version: 2

build_apk: &build_apk
  run:
    name: Build apk || ./gradlew assembleDebug
    command: ./gradlew clean assembleDebug --no-daemon --stacktrace
    
jobs:
  build:
    working_directory: ~/LeagueApp
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: app/build/reports
        destination: reports
    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: app/build/test-results
    - *build_apk
    - store_artifacts:
        path: app/build/outputs/apk/development
        destination: apks/
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

